
services:
  - type: web
    name: stock-analysis-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SERPER_API_KEY
        sync: false
      - key: BROWSERLESS_API_KEY
        sync: false
      - key: SEC_API_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: /health