financial_analysis:
  description: >
    Conduct a detailed analysis of {company_stock}'s financial health and market performance.
    Evaluate key financial metrics such as P/E ratio, EPS growth, revenue trends, margins,
    and debt-to-equity ratio. Benchmark the company against industry peers and overall market trends
    to identify strengths, weaknesses, and opportunities.
  expected_output: >
    A clear, structured assessment of {company_stock}'s financial standing that highlights its
    competitive position, recent performance, and any notable risks or advantages. 
    Ensure findings use the most recent data available.

research:
  description: >
    Collect and synthesize the latest news articles, press releases, analyst opinions,
    and market reports related to {company_stock} and its industry. Pay special attention
    to recent events, sentiment shifts, and upcoming milestones such as earnings calls,
    product launches, or regulatory updates.
  expected_output: >
    A comprehensive summary of recent developments, notable sentiment changes, and
    potential catalysts for {company_stock}. Clearly state the stock ticker {company_stock}
    and ensure information reflects the most up-to-date sources.

filings_analysis:
  description: >
    Review and analyze the most recent 10-Q and 10-K filings for {company_stock}.
    Focus on sections such as Management’s Discussion & Analysis (MD&A),
    financial statements, risk factors, and insider trading disclosures.
    Extract material insights that could influence investor decisions.
  expected_output: >
    A report highlighting significant findings from SEC filings, including risks,
    positive signals, and unusual activities. Provide context on how these findings
    may impact {company_stock}'s outlook.

recommend:
  description: >
    Integrate insights from the financial analysis, research, and SEC filings
    into a unified investment recommendation for {company_stock}.
    Consider fundamentals, market sentiment, regulatory risks, and insider activity
    to produce a well-balanced strategy. Include any relevant upcoming events
    (e.g., earnings announcements).
  expected_output: >
    A professional, detailed investment report for {company_stock}, clearly stating
    the recommended stance (Buy, Hold, Sell) and rationale. Use supporting evidence
    from all prior analyses. The report must be clearly formatted for readability.
    
    End with:
    ```
    Final Answer: <your full investment recommendation>
    ```